{{- if .Values.istio.enabled }}
{{- if .Values.crosscluster.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: infrabin
  namespace: infrabin
spec:
  hosts:
  - infrabin.example.com
  location: MESH_INTERNAL
  endpoints:
  - address: 172.17.0.1
    ports:
      http: 8080
  - address: 172.17.0.1
    ports:
      http: 9090
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
{{- end }}
{{- end }}