{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "infrabin.example.com"
  gateways:
  - infrabin
  - mesh
  http:
  - match:
    - gateways:
      - infrabin
    route:
    - destination:
        port:
          number: 80
        host: infrabin.infrabin.svc.cluster.local
  - match:
    - gateways:
      - mesh
    route:
    - destination:
        port:
          number: 80
        host: infrabin.example.com
{{- end }}
