# Istio chart values

global:
  controlPlaneSecurityEnabled: true
  mtls:
    enabled: true
  proxy:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
prometheus:
  enabled: true
mixer:
  policy:
    enabled: true
  telemetry:
    enabled: true
security:
  selfSigned: false
